<?php
return[
    'all'=>[
        'supervisor'=>[
            'readonly'=>[
                'id_projektu',
                'typ_projektu',
                'planovanie_rozpoctu',
                'datum_schvalenia_ID',
                'hyperlink_na_pi',
                'schvalenie_PI_na_PG',
                'datum_schvalenia_PI_na_PG',
                'pripomienky_k_PI',
                'hyperlink_na_pz',
                'schvalenie_PZ_na_PG',
                'datum_schvalenia_PZ_na_PG',
                'pripomienky_k_PZ',
                'verejna_praca',
                'celkom_BV_a_KV_vrat_DPH',
                'rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_bezne_rok_minus',
                'idea_bezne_rok_0',
                'idea_bezne_rok_1',
                'idea_bezne_rok_2',
                'idea_bezne_rok_3',
                'idea_bezne_rok_4',
                'idea_bezne_rok_5',
                'idea_bezne_rok_6',
                'idea_bezne_rok_7',
                'idea_bezne_rok_8',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_kapitalove_rok_minus',
                'idea_kapitalove_rok_0',
                'idea_kapitalove_rok_1',
                'idea_kapitalove_rok_2',
                'idea_kapitalove_rok_3',
                'idea_kapitalove_rok_4',
                'idea_kapitalove_rok_5',
                'idea_kapitalove_rok_6',
                'idea_kapitalove_rok_7',
                'idea_kapitalove_rok_8',
                'celkom_vrat_DPH',
                'rocne_prevadzkove_naklady_vrat_DPH',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_bezne_rok_minus',
                'zamer_bezne_rok_0',
                'zamer_bezne_rok_1',
                'zamer_bezne_rok_2',
                'zamer_bezne_rok_3',
                'zamer_bezne_rok_4',
                'zamer_bezne_rok_5',
                'zamer_bezne_rok_6',
                'zamer_bezne_rok_7',
                'zamer_bezne_rok_8',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_kapitalove_rok_minus',
                'zamer_kapitalove_rok_0',
                'zamer_kapitalove_rok_1',
                'zamer_kapitalove_rok_2',
                'zamer_kapitalove_rok_3',
                'zamer_kapitalove_rok_4',
                'zamer_kapitalove_rok_5',
                'zamer_kapitalove_rok_6',
                'zamer_kapitalove_rok_7',
                'zamer_kapitalove_rok_8',
                'bezne_prijmy_celkom_vrat_DPH',
                'bezne_prijmy_rok_minus',
                'bezne_prijmy_rok_0',
                'bezne_prijmy_rok_1',
                'bezne_prijmy_rok_2',
                'bezne_prijmy_rok_3',
                'bezne_prijmy_rok_4',
                'bezne_prijmy_rok_5',
                'bezne_prijmy_rok_6',
                'bezne_prijmy_rok_7',
                'bezne_prijmy_rok_8',
                'kapitalove_prijmy_celkom_vrat_DPH',
                'kapitalove_prijmy_rok_minus',
                'kapitalove_prijmy_rok_0',
                'kapitalove_prijmy_rok_1',
                'kapitalove_prijmy_rok_2',
                'kapitalove_prijmy_rok_3',
                'kapitalove_prijmy_rok_4',
                'kapitalove_prijmy_rok_5',
                'kapitalove_prijmy_rok_6',
                'kapitalove_prijmy_rok_7',
                'kapitalove_prijmy_rok_8',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'kategoria_projektu',
                'zadavatel_projektu',
                'projektovy_garant',
                'utvar_projektoveho_manazera',
                'projektovy_veduci',
                'mestska_cast',
                'priorita',
                'hashtagy',
                'specificke_atributy',
                'kvalifikovany_odhad_ceny_projektu',
                'financovanie_rok_minus',
                'financovanie_rok_0',
                'financovanie_rok_1',
                'financovanie_rok_2',
                'financovanie_rok_3',
                'financovanie_rok_4',
                'financovanie_rok_5',
                'financovanie_rok_6',
                'financovanie_rok_7',
                'financovanie_rok_8',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_DPH',
                'suvisiace_projekty',
                'mtl_log_status',
            ],
            'request'=>[
            ],
            'hide'=>[
            ]
        ],
        'projekt_vedenie'=>[
            'readonly'=>[
                'id_projektu',
                'typ_projektu',
                'planovanie_rozpoctu',
                'datum_schvalenia_ID',
                'hyperlink_na_pi',
                'schvalenie_PI_na_PG',
                'datum_schvalenia_PI_na_PG',
                'pripomienky_k_PI',
                'hyperlink_na_pz',
                'schvalenie_PZ_na_PG',
                'datum_schvalenia_PZ_na_PG',
                'pripomienky_k_PZ',
                'verejna_praca',
                'celkom_BV_a_KV_vrat_DPH',
                'rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_bezne_rok_minus',
                'idea_bezne_rok_0',
                'idea_bezne_rok_1',
                'idea_bezne_rok_2',
                'idea_bezne_rok_3',
                'idea_bezne_rok_4',
                'idea_bezne_rok_5',
                'idea_bezne_rok_6',
                'idea_bezne_rok_7',
                'idea_bezne_rok_8',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_kapitalove_rok_minus',
                'idea_kapitalove_rok_0',
                'idea_kapitalove_rok_1',
                'idea_kapitalove_rok_2',
                'idea_kapitalove_rok_3',
                'idea_kapitalove_rok_4',
                'idea_kapitalove_rok_5',
                'idea_kapitalove_rok_6',
                'idea_kapitalove_rok_7',
                'idea_kapitalove_rok_8',
                'celkom_vrat_DPH',
                'rocne_prevadzkove_naklady_vrat_DPH',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_bezne_rok_minus',
                'zamer_bezne_rok_0',
                'zamer_bezne_rok_1',
                'zamer_bezne_rok_2',
                'zamer_bezne_rok_3',
                'zamer_bezne_rok_4',
                'zamer_bezne_rok_5',
                'zamer_bezne_rok_6',
                'zamer_bezne_rok_7',
                'zamer_bezne_rok_8',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_kapitalove_rok_minus',
                'zamer_kapitalove_rok_0',
                'zamer_kapitalove_rok_1',
                'zamer_kapitalove_rok_2',
                'zamer_kapitalove_rok_3',
                'zamer_kapitalove_rok_4',
                'zamer_kapitalove_rok_5',
                'zamer_kapitalove_rok_6',
                'zamer_kapitalove_rok_7',
                'zamer_kapitalove_rok_8',
                'bezne_prijmy_celkom_vrat_DPH',
                'bezne_prijmy_rok_minus',
                'bezne_prijmy_rok_0',
                'bezne_prijmy_rok_1',
                'bezne_prijmy_rok_2',
                'bezne_prijmy_rok_3',
                'bezne_prijmy_rok_4',
                'bezne_prijmy_rok_5',
                'bezne_prijmy_rok_6',
                'bezne_prijmy_rok_7',
                'bezne_prijmy_rok_8',
                'kapitalove_prijmy_celkom_vrat_DPH',
                'kapitalove_prijmy_rok_minus',
                'kapitalove_prijmy_rok_0',
                'kapitalove_prijmy_rok_1',
                'kapitalove_prijmy_rok_2',
                'kapitalove_prijmy_rok_3',
                'kapitalove_prijmy_rok_4',
                'kapitalove_prijmy_rok_5',
                'kapitalove_prijmy_rok_6',
                'kapitalove_prijmy_rok_7',
                'kapitalove_prijmy_rok_8',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'kategoria_projektu',
                'zadavatel_projektu',
                'projektovy_garant',
                'utvar_projektoveho_manazera',
                'projektovy_veduci',
                'mestska_cast',
                'priorita',
                'hashtagy',
                'specificke_atributy',
                'kvalifikovany_odhad_ceny_projektu',
                'financovanie_rok_minus',
                'financovanie_rok_0',
                'financovanie_rok_1',
                'financovanie_rok_2',
                'financovanie_rok_3',
                'financovanie_rok_4',
                'financovanie_rok_5',
                'financovanie_rok_6',
                'financovanie_rok_7',
                'financovanie_rok_8',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_DPH',
                'suvisiace_projekty',
                'mtl_log_status',
            ],
            'request'=>[
            ],
            'hide'=>[

            ]
        ],
        'projekt_tim'=>[
            'readonly'=>[
                'id_projektu',
                'typ_projektu',
                'datum_zacatia_projektu_1',
                'datum_konca_projektu_1',
                'stav_projektu',
                'faza_projektu',
                //biela časť - aktivity,milniky,ich začiatky... asi sa dorieši len cez if podmienky...
                'datum_schvalenia_ID',
                'hyperlink_na_pi',
                'schvalenie_PI_na_PG',
                'datum_schvalenia_PI_na_PG',
                'pripomienky_k_PI',
                'hyperlink_na_pz',
                'schvalenie_PZ_na_PG',
                'datum_schvalenia_PZ_na_PG',
                'pripomienky_k_PZ',
                'verejna_praca',
                'najaktualnejsia_cena_projektu_vrat_DPH',
                'najaktualnejsie_rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'celkom_BV_a_KV_vrat_DPH',
                'rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_bezne_rok_minus',
                'idea_bezne_rok_0',
                'idea_bezne_rok_1',
                'idea_bezne_rok_2',
                'idea_bezne_rok_3',
                'idea_bezne_rok_4',
                'idea_bezne_rok_5',
                'idea_bezne_rok_6',
                'idea_bezne_rok_7',
                'idea_bezne_rok_8',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_kapitalove_rok_minus',
                'idea_kapitalove_rok_0',
                'idea_kapitalove_rok_1',
                'idea_kapitalove_rok_2',
                'idea_kapitalove_rok_3',
                'idea_kapitalove_rok_4',
                'idea_kapitalove_rok_5',
                'idea_kapitalove_rok_6',
                'idea_kapitalove_rok_7',
                'idea_kapitalove_rok_8',
                'celkom_vrat_DPH',
                'rocne_prevadzkove_naklady_vrat_DPH',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_bezne_rok_minus',
                'zamer_bezne_rok_0',
                'zamer_bezne_rok_1',
                'zamer_bezne_rok_2',
                'zamer_bezne_rok_3',
                'zamer_bezne_rok_4',
                'zamer_bezne_rok_5',
                'zamer_bezne_rok_6',
                'zamer_bezne_rok_7',
                'zamer_bezne_rok_8',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_kapitalove_rok_minus',
                'zamer_kapitalove_rok_0',
                'zamer_kapitalove_rok_1',
                'zamer_kapitalove_rok_2',
                'zamer_kapitalove_rok_3',
                'zamer_kapitalove_rok_4',
                'zamer_kapitalove_rok_5',
                'zamer_kapitalove_rok_6',
                'zamer_kapitalove_rok_7',
                'zamer_kapitalove_rok_8',
                'bezne_prijmy_celkom_vrat_DPH',
                'bezne_prijmy_rok_minus',
                'bezne_prijmy_rok_0',
                'bezne_prijmy_rok_1',
                'bezne_prijmy_rok_2',
                'bezne_prijmy_rok_3',
                'bezne_prijmy_rok_4',
                'bezne_prijmy_rok_5',
                'bezne_prijmy_rok_6',
                'bezne_prijmy_rok_7',
                'bezne_prijmy_rok_8',
                'kapitalove_prijmy_celkom_vrat_DPH',
                'kapitalove_prijmy_rok_minus',
                'kapitalove_prijmy_rok_0',
                'kapitalove_prijmy_rok_1',
                'kapitalove_prijmy_rok_2',
                'kapitalove_prijmy_rok_3',
                'kapitalove_prijmy_rok_4',
                'kapitalove_prijmy_rok_5',
                'kapitalove_prijmy_rok_6',
                'kapitalove_prijmy_rok_7',
                'kapitalove_prijmy_rok_8',

                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'kategoria_projektu',
                'zadavatel_projektu',
                'projektovy_garant',
                'utvar_projektoveho_manazera',
                'projektovy_veduci',
                'spolupracujuci_na_projekte_utvary_mesta',
                'spolupracujuci_na_projekte_organizacie_mesta',
                'externi_stakeholderi',
                'riadiace_gremium',
                'projektovy_tim',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'suma_externeho_financovania',
                'podiel_externeho_financovania_z_celkovej_ceny',
                'mestska_cast',
                'priorita',
                'hashtagy',

                'specificke_atributy',
                'link_pz_ulozisko',

                'kvalifikovany_odhad_ceny_projektu',
                'financovanie_rok_minus',
                'financovanie_rok_0',
                'financovanie_rok_1',
                'financovanie_rok_2',
                'financovanie_rok_3',
                'financovanie_rok_4',
                'financovanie_rok_5',
                'financovanie_rok_6',
                'financovanie_rok_7',
                'financovanie_rok_8',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_DPH',
                'suvisiace_projekty'
            ],
            'request'=>[],
            'hide'=>[
                //'zdroj_informacie_ku_kvalifikovanemu_odhadu',
                'reporting',
                'mtl_log_status',
              // 'poznamky',
                'planovanie_rozpoctu',
            ]
        ],
        'everyone'=>[
            'readonly'=>[
                'id_projektu',
                'typ_projektu',
                'datum_zacatia_projektu_1',
                'datum_konca_projektu_1',
                'stav_projektu',
                'faza_projektu',
                //biela časť - aktivity,milniky,ich začiatky... asi sa dorieši len cez if podmienky...
                'datum_schvalenia_PI_na_PG',
                'datum_schvalenia_PZ_na_PG',
                'pripomienky_k_PZ',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'kategoria_projektu',
                'zadavatel_projektu',
                'projektovy_veduci',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'mestska_cast',
                'priorita',
                'hashtagy',
            ],
            'request'=>[],
            'hide'=>[
                'zrealizovane_aktivity',
                'planovane_aktivity',
                'rizika_projektu',
                //'zdroj_informacie_ku_kvalifikovanemu_odhadu',
                'reporting',
                'mtl_log_status',
                //'poznamky',
                'planovanie_rozpoctu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'projektovy_garant',
                'utvar_projektoveho_manazera',
                'coop_utvary',
                'coop_organizacie',
               // 'externi_stakeholderi',
                'riadiace_gremium',
                'projektovy_tim',
                'suma_externeho_financovania',
                'externi_stakeholderi',
                'datum_schvalenia_ID',
                'id_schvalenie_pi_na_pg',
                'hyperlink_na_pi',
                'pripomienky_k_pi',
                'id_schvalenie_pz_na_pg',
                'hyperlink_na_pz',
                'pripomienky_k_pz',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'id_externe_financovanie',
                'id_priorita',
                'priorita',
                'podiel_externeho_financovania_z_celkovej_ceny',
                'hyperlink_na_ulozisko_projektu',
                'najaktualnejsie_rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'najaktualnejsia_cena_projektu_vrat_DPH',
                'max_rok',
                'suvisiace_projekty',
                'poznamky',
                'ryg',
                'muscow',
                //'datum_schvalenia_ID',
                //'hyperlink_na_pi',
                //'schvalenie_PI_na_PG',
                //'pripomienky_k_PI',
                //'hyperlink_na_pz',
                //'schvalenie_PZ_na_PG',
                //'podiel_externeho_financovania_z_celkovej_ceny',
                //'verejna_praca',
                'specificke_atributy'
                //'link_pz_ulozisko',

//                'celkom_BV_a_KV_vrat_DPH',
//                'rocne_prevadzkove_naklady_projektu_vrat_DPH',
//                'idea_bezne_ocakavane_rocne_naklady_projektu_s_DPH',
//                'idea_bezne_rok_minus',
//                'idea_bezne_rok_0',
//                'idea_bezne_rok_1',
//                'idea_bezne_rok_2',
//                'idea_bezne_rok_3',
//                'idea_bezne_rok_4',
//                'idea_bezne_rok_5',
//                'idea_bezne_rok_6',
//                'idea_bezne_rok_7',
//                'idea_bezne_rok_8',
//                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_DPH',
//                'idea_kapitalove_rok_minus',
//                'idea_kapitalove_rok_0',
//                'idea_kapitalove_rok_1',
//                'idea_kapitalove_rok_2',
//                'idea_kapitalove_rok_3',
//                'idea_kapitalove_rok_4',
//                'idea_kapitalove_rok_5',
//                'idea_kapitalove_rok_6',
//                'idea_kapitalove_rok_7',
//                'idea_kapitalove_rok_8',
//                'celkom_vrat_DPH',
//                'rocne_prevadzkove_naklady_vrat_DPH',
//                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
//                'zamer_bezne_rok_minus',
//                'zamer_bezne_rok_0',
//                'zamer_bezne_rok_1',
//                'zamer_bezne_rok_2',
//                'zamer_bezne_rok_3',
//                'zamer_bezne_rok_4',
//                'zamer_bezne_rok_5',
//                'zamer_bezne_rok_6',
//                'zamer_bezne_rok_7',
//                'zamer_bezne_rok_8',
//                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
//                'zamer_kapitalove_rok_minus',
//                'zamer_kapitalove_rok_0',
//                'zamer_kapitalove_rok_1',
//                'zamer_kapitalove_rok_2',
//                'zamer_kapitalove_rok_3',
//                'zamer_kapitalove_rok_4',
//                'zamer_kapitalove_rok_5',
//                'zamer_kapitalove_rok_6',
//                'zamer_kapitalove_rok_7',
//                'zamer_kapitalove_rok_8',
//                'bezne_prijmy_celkom_vrat_DPH',
//                'bezne_prijmy_rok_minus',
//                'bezne_prijmy_rok_0',
//                'bezne_prijmy_rok_1',
//                'bezne_prijmy_rok_2',
//                'bezne_prijmy_rok_3',
//                'bezne_prijmy_rok_4',
//                'bezne_prijmy_rok_5',
//                'bezne_prijmy_rok_6',
//                'bezne_prijmy_rok_7',
//                'bezne_prijmy_rok_8',
//                'kapitalove_prijmy_celkom_vrat_DPH',
//                'kapitalove_prijmy_rok_minus',
//                'kapitalove_prijmy_rok_0',
//                'kapitalove_prijmy_rok_1',
//                'kapitalove_prijmy_rok_2',
//                'kapitalove_prijmy_rok_3',
//                'kapitalove_prijmy_rok_4',
//                'kapitalove_prijmy_rok_5',
//                'kapitalove_prijmy_rok_6',
//                'kapitalove_prijmy_rok_7',
//                'kapitalove_prijmy_rok_8',
//                'kvalifikovany_odhad_ceny_projektu',
//                'financovanie_rok_minus',
//                'financovanie_rok_0',
//                'financovanie_rok_1',
//                'financovanie_rok_2',
//                'financovanie_rok_3',
//                'financovanie_rok_4',
//                'financovanie_rok_5',
//                'financovanie_rok_6',
//                'financovanie_rok_7',
//                'financovanie_rok_8',
//                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_DPH',
//                'suvisiace_projekty',
//
//                'strategCielPhsr' ,
//                'speciCielPhsr',
//                'programPhsr',
//                'planovanieRozpoctu',
//                'projektGarant',
//                'utvarProjektManager',
//                'coopUtvary',
//                'coopOrganizacie',
//                'projektTim',
//                'riadiaceGremium',
//                'speciAtributy'
            ]
        ],
        'procesny_partner'=>[
            'readonly'=>[
                'id_projektu',
                'typ_projektu',
                'datum_zacatia_projektu_1',
                'datum_konca_projektu_1',
                'stav_projektu',
                'faza_projektu',
                //biela časť - aktivity,milniky,ich začiatky... asi sa dorieši len cez if podmienky...
                'datum_schvalenia_PI_na_PG',
                'datum_schvalenia_PZ_na_PG',
                'pripomienky_k_PZ',
                'najaktualnejsia_cena_projektu_vrat_DPH',
                'najaktualnejsie_rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'kategoria_projektu',
                'zadavatel_projektu',
                'projektovy_veduci',

                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'suma_externeho_financovania',
                'mestska_cast',
                'priorita',
                'hashtagy',
                'zdroj_informacie_ku_kvalifikovanemu_odhadu',
                'reporting',
                'mtl_log_status',
                'poznamky',
                'planovanie_rozpoctu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'projektovy_garant',
                'utvar_projektoveho_manazera',
                'spolupracujuci_na_projekte_utvary_mesta',
                'spolupracujuci_na_projekte_organizacie_mesta',
                'externi_stakeholderi',
                'riadiace_gremium',
                'projektovy_tim',
                'hyperlink_na_pi',
                'schvalenie_PI_na_PG',
                'pripomienky_k_PI',
                'hyperlink_na_pz',
                'schvalenie_PZ_na_PG',
                'podiel_externeho_financovania_z_celkovej_ceny',
                'verejna_praca',
                'specificke_atributy',
                'link_pz_ulozisko',

                'celkom_BV_a_KV_vrat_DPH',
                'rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_bezne_rok_minus',
                'idea_bezne_rok_0',
                'idea_bezne_rok_1',
                'idea_bezne_rok_2',
                'idea_bezne_rok_3',
                'idea_bezne_rok_4',
                'idea_bezne_rok_5',
                'idea_bezne_rok_6',
                'idea_bezne_rok_7',
                'idea_bezne_rok_8',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_DPH',
                'idea_kapitalove_rok_minus',
                'idea_kapitalove_rok_0',
                'idea_kapitalove_rok_1',
                'idea_kapitalove_rok_2',
                'idea_kapitalove_rok_3',
                'idea_kapitalove_rok_4',
                'idea_kapitalove_rok_5',
                'idea_kapitalove_rok_6',
                'idea_kapitalove_rok_7',
                'idea_kapitalove_rok_8',
                'celkom_vrat_DPH',
                'rocne_prevadzkove_naklady_vrat_DPH',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_bezne_rok_minus',
                'zamer_bezne_rok_0',
                'zamer_bezne_rok_1',
                'zamer_bezne_rok_2',
                'zamer_bezne_rok_3',
                'zamer_bezne_rok_4',
                'zamer_bezne_rok_5',
                'zamer_bezne_rok_6',
                'zamer_bezne_rok_7',
                'zamer_bezne_rok_8',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_DPH',
                'zamer_kapitalove_rok_minus',
                'zamer_kapitalove_rok_0',
                'zamer_kapitalove_rok_1',
                'zamer_kapitalove_rok_2',
                'zamer_kapitalove_rok_3',
                'zamer_kapitalove_rok_4',
                'zamer_kapitalove_rok_5',
                'zamer_kapitalove_rok_6',
                'zamer_kapitalove_rok_7',
                'zamer_kapitalove_rok_8',
                'bezne_prijmy_celkom_vrat_DPH',
                'bezne_prijmy_rok_minus',
                'bezne_prijmy_rok_0',
                'bezne_prijmy_rok_1',
                'bezne_prijmy_rok_2',
                'bezne_prijmy_rok_3',
                'bezne_prijmy_rok_4',
                'bezne_prijmy_rok_5',
                'bezne_prijmy_rok_6',
                'bezne_prijmy_rok_7',
                'bezne_prijmy_rok_8',
                'kapitalove_prijmy_celkom_vrat_DPH',
                'kapitalove_prijmy_rok_minus',
                'kapitalove_prijmy_rok_0',
                'kapitalove_prijmy_rok_1',
                'kapitalove_prijmy_rok_2',
                'kapitalove_prijmy_rok_3',
                'kapitalove_prijmy_rok_4',
                'kapitalove_prijmy_rok_5',
                'kapitalove_prijmy_rok_6',
                'kapitalove_prijmy_rok_7',
                'kapitalove_prijmy_rok_8',
                'kvalifikovany_odhad_ceny_projektu',
                'financovanie_rok_minus',
                'financovanie_rok_0',
                'financovanie_rok_1',
                'financovanie_rok_2',
                'financovanie_rok_3',
                'financovanie_rok_4',
                'financovanie_rok_5',
                'financovanie_rok_6',
                'financovanie_rok_7',
                'financovanie_rok_8',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_DPH',
                'suvisiace_projekty'
            ],
            'request'=>[],
            'hide'=>[
                'datum_schvalenia_ID',
                'poslednaUkoncenaAktivita',
            ]
        ],
        'admin'=>[
            'readonly'=>[],
            'request'=>[],
            'hide'=>[
            ]
]
    ]
];
