<?php
return[
    'rights'=>[
        'admin'=>[
            'write'=>[
                'id_pp',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'typ_projektu',
                'kategoria',
                'ryg',
                'muscow',
                'prioritne_oblasti',
                'stav_projektu',
                'faza_projektu',
                'datum_zacatia_projektu',
                'datum_konca_projektu',
                'zrealizovane_aktivity',
                'planovane_aktivity_na_najblizsi_tyzden',
                'rizika_projektu',
                'mtl',
                'mtl_log_status',
                'komentar',
                'value','headerTitle','zodpovedni','zaciatok_aktivity','koniec_aktivity',
                'skutocny_zaciatok_aktivity','skutocny_koniec_aktivity',
                'magistratny_garant',
                'utvar_magistratneho_garanta',
                'politicky_garant',
                'zadavatel_projektu',
                'projektovy_garant',
                'projektovy_manager',
                'utvar_projektoveho_managera',
                'coop_utvary',
                'coop_organizacie',
                'externi_stakeholderi',
                'sprava',
                'udrzba',
                'riadiace_gremium',
                'projektovy_tim',
                'datum_schvalenie_id',
                'schvalenie_pi_na_pg',
                'datum_schvalenia_pi_na_pg',
                'hyperlink_na_pi',
                'pripomienky_k_pi',
                'schvalenie_pz_na_pg',
                'datum_schvalenia_pz_na_pg',
                'hyperlink_na_pz',
                'pripomienky_k_pz',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'suma_externeho_financovania',
                'podiel_externeho_financovania_z_celkovej_ceny',
                'mestska_cast',
                'id_priorita',
                'id_priorita_new',
                'verejna_praca',
                'suvisiace_projekty',
                'hashtag',
                'specificke_atributy',
                'hyperlink_na_ulozisko_projektu',
                'najaktualnejsia_cena_projektu_vrat_DPH',
                'najaktual_rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'celkom_bv_a_kv_vrat_dph',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_dph',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_dph',
                'rocne_prevadzkove_naklady_projektu_vrat_dph',
                'bezne_prijmy_celkom_vrat_dph',
                'celkom_vrat_dph',
                'kvalifikovany_odhad',
                'projektova_idea',
                'projektovy_zamer',
                'kapitalove_prijmy_celkom_vrat_dph',
                'rocne_prevadzkove_naklady_vrat_dph',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'kvalifikovany_odhad_ceny_projektu',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_dph',
                'zdroj_info_kvalif_odhad',
                'max_rok',
                'reporting',
                'planovanie_rozpoctu',
                'poznamky'

            ],
            'read'=>[

            ],
            'hide' =>[],
        ],

        'supervisor'=>[
            'write'=>[
                'zrealizovane_aktivity',
                'planovane_aktivity_na_najblizsi_tyzden',
                'rizika_projektu',
                'mtl',
                'skutocny_zaciatok_aktivity',
                'skutocny_koniec_aktivity',
                'hyperlink_na_ulozisko_projektu',
                'komentar',
                'datum_zacatia_projektu', //pridane
                'datum_konca_projektu', //pridane
                'faza_projektu', //pridane
                'stav_projektu', //pridane
                'rizika_projektu', //pridane
                'coop_utvary', //pridane
                'coop_organizacie', //pridane
                'externi_stakeholderi',  //pridane
                'sprava',  //pridane
                'udrzba',  //pridane
                'riadiace_gremium', //pridane
                'projektovy_tim',   //pridane
                'externe_financovanie',  //pridane
                'zdroj_externeho_financovania',  //pridane
                'suma_externeho_financovania',   //pridane
                'podiel_externeho_financovania_z_celkovej_ceny',  //pridane
                'najaktualnejsia_cena_projektu_vrat_DPH', //pridane
                'najaktual_rocne_prevadzkove_naklady_projektu_vrat_DPH',  //pridane
            ],
            'read'=>[
                'id_pp',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'typ_projektu',
                'kategoria',
                'muscow',
                'prioritne_oblasti',
                'magistratny_garant',
                'utvar_magistratneho_garanta',
                'politicky_garant',
                'zadavatel_projektu',
                'projektovy_garant',
                'projektovy_manager',
                'utvar_projektoveho_managera',
                'datum_schvalenie_id',
                'schvalenie_pi_na_pg',
                'datum_schvalenia_pi_na_pg',
                'hyperlink_na_pi',
                'pripomienky_k_pi',
                'schvalenie_pz_na_pg',
                'datum_schvalenia_pz_na_pg',
                'hyperlink_na_pz',
                'pripomienky_k_pz',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'mestska_cast',
                'id_priorita',
                'id_priorita_new',
                'verejna_praca',
                'suvisiace_projekty',
                'hashtag',
                'specificke_atributy',
                'celkom_bv_a_kv_vrat_dph',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_dph',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_dph',
                'rocne_prevadzkove_naklady_projektu_vrat_dph',
                'bezne_prijmy_celkom_vrat_dph',
                'celkom_vrat_dph',
                'kvalifikovany_odhad',
                'projektova_idea',
                'projektovy_zamer',
                'kapitalove_prijmy_celkom_vrat_dph',
                'rocne_prevadzkove_naklady_vrat_dph',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'kvalifikovany_odhad_ceny_projektu',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_dph',
                'ryg', //pridane
                'value', 'headerTitle', 'zodpovedni', //pridane
                'zaciatok_aktivity', //pridane,
                'koniec_aktivity', //pridane,
            ]
        ],
        'projekt_vedenie'=>[
            'write'=>[
                'zrealizovane_aktivity',
                'planovane_aktivity_na_najblizsi_tyzden',
                'rizika_projektu',
                'mtl',
                'skutocny_zaciatok_aktivity',
                'skutocny_koniec_aktivity',
                'hyperlink_na_ulozisko_projektu',
                'komentar',
                'datum_zacatia_projektu', //pridane
                'datum_konca_projektu', //pridane
                'faza_projektu', //pridane
                'stav_projektu', //pridane
                'rizika_projektu', //pridane
                'coop_utvary', //pridane
                'coop_organizacie', //pridane
                'externi_stakeholderi',  //pridane
                'sprava',  //pridane
                'udrzba',  //pridane
                'riadiace_gremium', //pridane
                'projektovy_tim',   //pridane
                'externe_financovanie',  //pridane
                'zdroj_externeho_financovania',  //pridane
                'suma_externeho_financovania',   //pridane
                'podiel_externeho_financovania_z_celkovej_ceny',  //pridane
                'najaktualnejsia_cena_projektu_vrat_DPH', //pridane
                'najaktual_rocne_prevadzkove_naklady_projektu_vrat_DPH',  //pridane
            ],
            'read'=>[
                'id_pp',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'typ_projektu',
                'kategoria',
                'muscow',
                'prioritne_oblasti',
                'magistratny_garant',
                'utvar_magistratneho_garanta',
                'politicky_garant',
                'zadavatel_projektu',
                'projektovy_garant',
                'projektovy_manager',
                'utvar_projektoveho_managera',
                'datum_schvalenie_id',
                'schvalenie_pi_na_pg',
                'datum_schvalenia_pi_na_pg',
                'hyperlink_na_pi',
                'pripomienky_k_pi',
                'schvalenie_pz_na_pg',
                'datum_schvalenia_pz_na_pg',
                'hyperlink_na_pz',
                'pripomienky_k_pz',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'mestska_cast',
                'id_priorita',
                'id_priorita_new',
                'verejna_praca',
                'suvisiace_projekty',
                'hashtag',
                'specificke_atributy',
                'celkom_bv_a_kv_vrat_dph',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_dph',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_dph',
                'rocne_prevadzkove_naklady_projektu_vrat_dph',
                'bezne_prijmy_celkom_vrat_dph',
                'celkom_vrat_dph',
                'kvalifikovany_odhad',
                'projektova_idea',
                'projektovy_zamer',
                'kapitalove_prijmy_celkom_vrat_dph',
                'rocne_prevadzkove_naklady_vrat_dph',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'kvalifikovany_odhad_ceny_projektu',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_dph',
                'ryg', //pridane
                'value', 'headerTitle', 'zodpovedni', //pridane
                'zaciatok_aktivity', //pridane,
                'koniec_aktivity', //pridane,
            ]
        ],
        'projekt_tim'=>[
            'write'=>[

            ],
            'read'=>[
                'id_pp',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'typ_projektu',
                'kategoria',
                'ryg',
                'muscow',
                'stav_projektu',
                'faza_projektu',
                'datum_zacatia_projektu',
                'datum_konca_projektu',
                'zrealizovane_aktivity',
                'planovane_aktivity_na_najblizsi_tyzden',
                'rizika_projektu',
                'mtl',
                'komentar',
                'value','headerTitle','zodpovedni','zaciatok_aktivity','koniec_aktivity',
                'skutocny_zaciatok_aktivity','skutocny_koniec_aktivity',
                'magistratny_garant',
                'utvar_magistratneho_garanta',
                'politicky_garant',
                'zadavatel_projektu',
                'projektovy_garant',
                'projektovy_manager',
                'utvar_projektoveho_managera',
                'coop_utvary',
                'coop_organizacie',
                'externi_stakeholderi',
                'sprava',
                'udrzba',
                'riadiace_gremium',
                'projektovy_tim',
                'datum_schvalenie_id',
                'schvalenie_pi_na_pg',
                'datum_schvalenia_pi_na_pg',
                'hyperlink_na_pi',
                'pripomienky_k_pi',
                'schvalenie_pz_na_pg',
                'datum_schvalenia_pz_na_pg',
                'hyperlink_na_pz',
                'pripomienky_k_pz',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'suma_externeho_financovania',
                'podiel_externeho_financovania_z_celkovej_ceny',
                'mestska_cast',
                'id_priorita',
                'id_priorita_new',
                'verejna_praca',
                'suvisiace_projekty',
                'hashtag',
                'specificke_atributy',
                'hyperlink_na_ulozisko_projektu',
                'najaktualnejsia_cena_projektu_vrat_DPH',
                'najaktual_rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'celkom_bv_a_kv_vrat_dph',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_dph',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_dph',
                'rocne_prevadzkove_naklady_projektu_vrat_dph',
                'bezne_prijmy_celkom_vrat_dph',
                'celkom_vrat_dph',
                'kvalifikovany_odhad',
                'projektova_idea',
                'projektovy_zamer',
                'kapitalove_prijmy_celkom_vrat_dph',
                'rocne_prevadzkove_naklady_vrat_dph',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'kvalifikovany_odhad_ceny_projektu',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_dph',
            ]
        ],
        'everyone'=>[
            'write'=>[

            ],
            'read'=>[
                'id_pp',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'typ_projektu',
                'kategoria',
                'ryg',
                'muscow',
                'prioritne_oblasti',
                'stav_projektu',
                'faza_projektu',
                'datum_zacatia_projektu',
                'datum_konca_projektu',
                'mtl',
                'magistratny_garant',
                'utvar_magistratneho_garanta',
                'politicky_garant',
                'zadavatel_projektu',
                'projektovy_manager',
                'sprava',
                'udrzba',
                'datum_schvalenia_pi_na_pg',
                'datum_schvalenia_pz_na_pg',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'suma_externeho_financovania',
                'mestska_cast',
                'id_priorita',
                'id_priorita_new',
                'suvisiace_projekty',
                'hashtag',
            ],
            'hide' =>[
                'politicky_garant',
            ],
        ],
        'procesny_partner'=>[
            'write'=>[
                'ryg',
                'muscow',
            ],
            'read'=>[
                'id_pp',
                'nazov_projektu',
                'alt_nazov_projektu',
                'ciel_projektu',
                'strategicky_ciel_PHSR',
                'specificky_ciel_PHSR',
                'program',
                'meratelny_vystupovy_ukazovatel',
                'typ_projektu',
                'kategoria',
                'prioritne_oblasti',
                'stav_projektu',
                'faza_projektu',
                'datum_zacatia_projektu',
                'datum_konca_projektu',
                'zrealizovane_aktivity',
                'planovane_aktivity_na_najblizsi_tyzden',
                'rizika_projektu',
                'mtl',
                'komentar',
                'value','headerTitle','zodpovedni','zaciatok_aktivity','koniec_aktivity',
                'skutocny_zaciatok_aktivity','skutocny_koniec_aktivity',
                'magistratny_garant',
                'utvar_magistratneho_garanta',
                'politicky_garant',
                'zadavatel_projektu',
                'projektovy_garant',
                'projektovy_manager',
                'utvar_projektoveho_managera',
                'coop_utvary',
                'coop_organizacie',
                'externi_stakeholderi',
                'sprava',
                'udrzba',
                'riadiace_gremium',
                'projektovy_tim',
                'schvalenie_pi_na_pg',
                'datum_schvalenia_pi_na_pg',
                'hyperlink_na_pi',
                'pripomienky_k_pi',
                'schvalenie_pz_na_pg',
                'datum_schvalenia_pz_na_pg',
                'hyperlink_na_pz',
                'pripomienky_k_pz',
                'datum_schvalenia_projektu_ppp',
                'datum_schvalenia_projektu_msz',
                'externe_financovanie',
                'zdroj_externeho_financovania',
                'suma_externeho_financovania',
                'podiel_externeho_financovania_z_celkovej_ceny',
                'mestska_cast',
                'id_priorita',
                'id_priorita_new',
                'verejna_praca',
                'suvisiace_projekty',
                'hashtag',
                'specificke_atributy',
                'hyperlink_na_ulozisko_projektu',
                'najaktualnejsia_cena_projektu_vrat_DPH',
                'najaktual_rocne_prevadzkove_naklady_projektu_vrat_DPH',
                'celkom_bv_a_kv_vrat_dph',
                'idea_bezne_ocakavane_rocne_naklady_projektu_s_dph',
                'idea_kapitalove_ocakavane_rocne_naklady_projektu_s_dph',
                'rocne_prevadzkove_naklady_projektu_vrat_dph',
                'bezne_prijmy_celkom_vrat_dph',
                'celkom_vrat_dph',
                'kvalifikovany_odhad',
                'projektova_idea',
                'projektovy_zamer',
                'kapitalove_prijmy_celkom_vrat_dph',
                'rocne_prevadzkove_naklady_vrat_dph',
                'zamer_bezne_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'zamer_kapitalove_aktualne_ocakavane_rocne_naklady_projektu_s_dph',
                'kvalifikovany_odhad_ceny_projektu',
                'kvalifikovany_odhad_rocnych_prevadzkovych_nakladov_vrat_dph',
                'zdroj_info_kvalif_odhad',
                'planovanie_rozpoctu',
            ]
        ],
    ]
];

