export const columns = [
    {
        key: "mtl",
        title: "Semafory",
        width: 64,
    },
    {
        key: "id",
        title: "ID",
        width: 75,
    },
    {
        key: "nazov_projektu",
        title: "Názov projektu",
        width: 350,
    },
    {
        key: "alt_nazov_projektu",
        title: "Rozšírený názov / Doplnok názvu",
        width: 350,
    },
    {
        key: "ciel_projektu",
        title: "Cieľ projektu",
        width: 200,
    },
    {
        key: "strategicky_ciel_PHSR",
        title: "Strategický cieľ PHSR",
        width: 200,
    },
    {
        key: "specificky_ciel_PHSR",
        title: "Špecifický cieľ PHSR",
        width: 200,
    },
    {
        key: "program",
        title: "Program",
        width: 200,
    },
    {
        key: "meratelny_vystupovy_ukazovatel",
        title: "Merateľný výstupový ukazovateľ",
        width: 200,
    },
    {
        key: "prioritne_oblasti",
        title: "Prioritné oblasti",
        width: 200,
    },
    {
        key: "typ_projektu",
        title: "Typ projektu",
        width: 200,
    },
    {
        key: "kategoria_projektu",
        title: "Kategória projektu",
        width: 200,
    },
    {
        key: "ryg",
        title: "RYG",
        width: 150,
    },
    {
        key: "muscow",
        title: "MuSCow",
        width: 150,
    },
    {
        key: "planovanie_rozpoctu",
        title: "Plánovanie rozpočtu",
        width: 200,
    },
    {
        key: "datum_zacatia_projektu",
        title: "Plánovaný dátum začiatku projektu",
        width: 150,
        date: "m.Y",
    },
    {
        key: "datum_konca_projektu",
        title: "Plánovaný dátum konca projektu",
        width: 150,
        date: "m.Y",
    },
    {
        key: "stav_projektu",
        title: "Stav projektu",
        width: 200,
    },
    {
        key: "faza_projektu",
        title: "Fáza projektu",
        width: 200,
    },
    {
        key: "zrealizovane_aktivity",
        title: "Zrealizované aktivity za posledný týždeň",
        width: 250,
    },
    {
        key: "planovane_aktivity",
        title: "Plánované aktivity na najbližší týždeň",
        width: 250,
    },
    {
        key: "rizika_projektu",
        title: "Riziká projektu",
        width: 250,
    },
    {
        key: "posledna_ukoncena_aktivita",
        title: "Posledná ukončená aktivita",
        width: 250,
    },
    {
        key: "magistratny_garant",
        title: "Magistrátny garant",
        width: 200,
    },
    {
        key: "politicky_garant",
        title: "Politický garant",
        width: 200,
    },
    {
        key: "utvar_projektoveho_manazera",
        title: "Útvar projektového manažéra",
        width: 200,
    },
    {
        key: "projektovy_manazer",
        title: "Projektový manažér",
        width: 200,
    },
    {
        key: "coop_utvary",
        title: "Spolupracujúci na projekte: Útvary magistrátu",
        width: 200,
    },
    {
        key: "coop_organizacie",
        title: "Spolupracujúci na projekte: Organizácie mesta",
        width: 200,
    },
    {
        key: "projektovy_tim",
        title: "Projektový tím",
        width: 200,
    },
    {
        key: "externi_stakeholderi",
        title: "Externí stakeholderi",
        width: 200,
    },
    {
        key: "sprava",
        title: "Správa",
        width: 200,
    },
    {
        key: "udrzba",
        title: "Údržba",
        width: 200,
    },
    {
        key: "riadiace_gremium",
        title: "Riadiace grémium",
        width: 200,
    },
    {
        key: "datum_schvalenia_ID",
        title: "Dátum schválenia projektu",
        width: 150,
        date: "m.Y",
    },
    {
        key: "id_schvalenie_pi_na_pg",
        title: "Schválenie PI na PG",
        width: 150,
    },
    {
        key: "hyperlink_na_pi",
        title: "Hyperlink na PI",
        width: 300,
    },
    {
        key: "pripomienky_k_pi",
        title: "Pripomienky k PI",
        width: 200,
    },
    {
        key: "datum_schvalenie_pi_na_pg",
        title: "Dátum schválenia PI na PG",
        width: 150,
        date: "m.Y",
    },
    {
        key: "id_schvalenie_pz_na_pg",
        title: "Schválenie PZ na PG",
        width: 150,
    },
    {
        key: "datum_schvalenie_pz_na_pg",
        title: "Dátum schválenia PZ na PG",
        width: 150,
        date: "m.Y",
    },
    {
        key: "hyperlink_na_pz",
        title: "Hyperlink na PZ",
        width: 300,
    },
    {
        key: "pripomienky_k_pz",
        title: "Pripomienky k PZ",
        width: 200,
    },
    {
        key: "datum_schvalenia_projektu_ppp",
        title: "Dátum schválenia projektu na PPP",
        width: 150,
        date: "m.Y",
    },
    {
        key: "datum_schvalenia_projektu_msz",
        title: "Dátum schválenia projektu na MSZ",
        width: 150,
        date: "m.Y",
    },
    {
        key: "id_externe_financovanie",
        title: "Externé financovanie",
        width: 200,
    },
    {
        key: "suma_externeho_financovania",
        title: "Suma externého financovania",
        width: 200,
    },
    {
        key: "id_priorita",
        title: "Priorita",
        width: 200,
    },
    {
        key: "priorita",
        title: "Politická priorita",
        width: 200,
    },
    {
        key: "zdroj_externeho_financovania",
        title: "Zdroj externého financovania",
        width: 200,
    },
    {
        key: "podiel_externeho_financovania_z_celkovej_ceny",
        title: "Podiel externého financovania",
        width: 200,
    },
    {
        key: "verejna_praca",
        title: "Verejná práca",
        width: 200,
    },
    {
        key: "mestska_cast",
        title: "Mestská časť",
        width: 200,
    },
    {
        key: "specificke_atributy",
        title: "Špecifické atribúty",
        width: 200,
    },
    {
        key: "hyperlink_na_ulozisko_projektu",
        title: "Hyperlink na úložisko projektu",
        width: 300,
    },
    {
        key: "najaktualnejsia_cena_projektu_vrat_DPH",
        title: "Najaktuálnejšia cena projektu vrátane DPH",
        width: 300,
    },
    {
        key: "najaktualnejsie_rocne_prevadzkove_naklady_projektu_vrat_DPH",
        title: "Najaktuálnejšie ročné prevádzkové náklady projektu vrátane DPH",
        width: 300,
    },
    {
        key: "max_rok",
        title: "Maximálny rok",
        width: 150,
    },
    {
        key: "suvisiace_projekty",
        title: "Súvisiace projekty",
        width: 200,
    },
    {
        key: "hashtagy",
        title: "Hashtagy",
        width: 200,
    },
    {
        key: "reporting",
        title: "Reporting",
        width: 200,
    },
    {
        key: "mtl_log_status",
        title: "Stav reportingu za minulý týždeň",
        width: 200,
    },
    {
        key: "poznamky",
        title: "Poznámky",
        width: 200,
    },
];
const defaultHiddenColumns = [
    "alt_nazov_projektu",
    "ciel_projektu",
    "strategicky_ciel_PHSR",
    "specificky_ciel_PHSR",
    "program",
    "meratelny_vystupovy_ukazovatel",
    "prioritne_oblasti",
    "planovanie_rozpoctu",
    "datum_zacatia_projektu",
    "datum_konca_projektu",
    "faza_projektu",
    "ryg",
    "muscow",
    "projektovy_garant",
    "utvar_projektoveho_manazera",
    "coop_utvary",
    "coop_organizacie",
    "projektovy_tim",
    "sprava",
    "udrzba",
    "riadiace_gremium",
    "datum_schvalenie_pi_na_pg",
    "datum_schvalenie_pz_na_pg",
    "zdroj_externeho_financovania",
    "specificke_atributy",
    "hashtagy",
    "externi_stakeholderi",
    "datum_schvalenia_ID",
    "id_schvalenie_pi_na_pg",
    "hyperlink_na_pi",
    "pripomienky_k_pi",
    "id_schvalenie_pz_na_pg",
    "hyperlink_na_pz",
    "pripomienky_k_pz",
    "datum_schvalenia_projektu_ppp",
    "datum_schvalenia_projektu_msz",
    "id_externe_financovanie",
    "id_priorita",
    "priorita",
    "podiel_externeho_financovania_z_celkovej_ceny",
    "hyperlink_na_ulozisko_projektu",
    "najaktualnejsie_rocne_prevadzkove_naklady_projektu_vrat_DPH",
    "max_rok",
    "suvisiace_projekty",
    "poznamky",
];
export const colummsWithAttributes = columns.map((column) => ({
    ...column,
    minWidth: column.width,
    visible: !defaultHiddenColumns.includes(column.key),
    filter: {
        open: false,
        value: [],
        list: [],
    },
    settings: false,
}));

export const currencyFields = ["suma_externeho_financovania", "najaktualnejsia_cena_projektu_vrat_DPH", "najaktualnejsie_rocne_prevadzkove_naklady_projektu_vrat_DPH"];
