name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install composer packages
        uses: ramsey/composer-install@v3

      - name: Print version
        run: php -v

#      - name: Run PHPCS
#        run: composer cs

      - name: PHPCS #2
        uses: szepeviktor/phpcs-ruleset-validator@v0.4.0
        with:
          xml_ruleset: rulesetCS.xml