name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ramsey/composer-install@v3

      # now run your PHPCS package
      - name: Run PHPCS
        run: composer cs