name: CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install composer packages
        uses: ramsey/composer-install@v3

      - name: Print version
        run: php -v

      - name: ls
        run: pwd && ls -al

      - name: Run PHPCS
        run: composer cs

      - name: Upload artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  code-check:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      - name: ls
        run: pwd && ls -al

      - name: Run PHPCS
        run: composer cs

#  deploy:
#    runs-on: self-hosted
#    steps:
#      - name: execute remote ssh commands
#        uses: appleboy/ssh-action@v1
#        with:
#          host: 192.168.0.44
#          username: root
#          port: 22
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            whoami
#            pwd
#            ls -al
#
