name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install composer packages
        uses: ramsey/composer-install@v3

      - name: Print version
        run: php -v

      - name: Run PHPCS
        run: composer cs
