name: CI

env:
  DOCKER_IMAGE_NAME: ga
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REGISTRY_SPACE: petbiqsab

on:
  push:
    tags:
      - '*'
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs:
  build-and-check-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install composer packages
        uses: ramsey/composer-install@v3

      - name: Print version
        run: php -v

      - name: Lint
        run: composer lint

      - name: VarDump check
        run: composer var-dump-check

      - name: Upload artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .
          include-hidden-files: true

  build-and-push-image:
    if: github.ref_name == 'develop' || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest
    needs: build-and-check-app
    steps:
      - name: Download artifact from build-app job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Create .env file
        run: cp .env.example .env

      - name: Remove composer dev packages
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--no-dev"

      - name: Print content
        run: ls -al .

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Login to Docker Registry
#        uses: docker/login-action@v3
#        with:
#          registry: ${{ env.DOCKER_REGISTRY }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Get the tag name
#        id: get_tag
#        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_tag.outputs.TAG }}
