name: CI

env:
  DOCKER_IMAGE_NAME: ga
  DOCKER_REGISTRY: ghcr.io
  DOCKER_REGISTRY_SPACE: petbiqsab

on:
  push:
    tags:
      - '*'
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs:
  build-app:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4

      - name: Install composer packages
        uses: ramsey/composer-install@v3

      - name: Print version
        run: php -v

      - name: ls
        run: cd vendor/bin && pwd && ls -al

      - name: Run PHPCS
        run: composer cs

      - name: Upload artifact for next job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  code-check:
    if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build-app
    steps:
      - name: Download artifact from build-app job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: ls
        run: cd vendor/bin && pwd && ls -al

      - name: Run PHPCS
        run: |
          chmod +x vendor/bin/*
          ls -al vendor/bin
          composer cs

  build-and-push-image-branch:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    needs: code-check
    steps:
      - name: Download artifact from build-app job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:develop
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

  build-and-push-image-tag:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: code-check
    steps:
      - name: Download artifact from build-app job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get the tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REGISTRY_SPACE }}/${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max